services:
  - type: web
    name: your-interviewer-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        fromService:
          type: web
          name: your-interviewer-app
          property: host
    healthCheckPath: /